In [1]:
import bq_helper
from bq_helper import BigQueryHelper

ghnp = bq_helper.BigQueryHelper(active_project="bigquery-public-data",
                                   dataset_name="world_bank_health_population")

In [2]:
bq_assistant = BigQueryHelper("bigquery-public-data", "world_bank_health_population")
bq_assistant.list_tables()

['country_series_definitions',
 'country_summary',
 'health_nutrition_population',
 'series_summary',
 'series_times']

In [3]:
bq_assistant.head("health_nutrition_population", num_rows=30)

,country_name,country_code,indicator_name,indicator_code,year,value
0,Uzbekistan,UZB,"Unemployment, male (% of male labor force)",SL.UEM.TOTL.MA.ZS,2018,6.936000e+00
1,Nepal,NPL,"Unemployment, male (% of male labor force)",SL.UEM.TOTL.MA.ZS,2018,3.187000e+00
2,Least developed countries: UN classification,LDC,"Unemployment, female (% of female labor force)",SL.UEM.TOTL.FE.ZS,2018,6.417805e+00
3,Mexico,MEX,"Unemployment, male (% of male labor force)",SL.UEM.TOTL.MA.ZS,2018,3.268000e+00
4,Cuba,CUB,"Unemployment, male (% of male labor force)",SL.UEM.TOTL.MA.ZS,2018,2.395000e+00
5,Central African Republic,CAF,"Unemployment, female (% of female labor force)",SL.UEM.TOTL.FE.ZS,2018,6.483000e+00
6,Lebanon,LBN,"Labor force, total",SL.TLF.TOTL.IN,2018,2.229303e+06
7,Azerbaijan,AZE,"Unemployment, male (% of male labor force)",SL.UEM.TOTL.MA.ZS,2018,4.686000e+00
8,Slovak Republic,SVK,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2018,7.268000e+00
9,South Africa,ZAF,"Unemployment, male (% of male labor force)",SL.UEM.TOTL.MA.ZS,2018,2.559000e+01
10,Namibia,NAM,"Labor force, female (% of total labor force)",SL.TLF.TOTL.FE.ZS,2018,4.954466e+01
11,El Salvador,SLV,"Unemployment, male (% of male labor force)",SL.UEM.TOTL.MA.ZS,2018,5.108000e+00
12,East Asia & Pacific (IDA & IBRD countries),TEA,"Labor force, female (% of total labor force)",SL.TLF.TOTL.FE.ZS,2018,4.304005e+01
13,Samoa,WSM,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2018,8.098000e+00
14,Central Europe and the Baltics,CEB,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2018,4.680785e+00
15,Pakistan,PAK,"Unemployment, female (% of female labor force)",SL.UEM.TOTL.FE.ZS,2018,7.295000e+00
16,Bulgaria,BGR,"Labor force, total",SL.TLF.TOTL.IN,2018,3.211189e+06
17,Guam,GUM,"Labor force, total",SL.TLF.TOTL.IN,2018,8.097200e+04
18,Samoa,WSM,"Unemployment, female (% of female labor force)",SL.UEM.TOTL.FE.ZS,2018,9.636000e+00
19,Timor-Leste,TLS,"Unemployment, male (% of male labor force)",SL.UEM.TOTL.MA.ZS,2018,2.989000e+00
20,Solomon Islands,SLB,"Unemployment, male (% of male labor force)",SL.UEM.TOTL.MA.ZS,2018,1.972000e+00
21,Burundi,BDI,"Unemployment, male (% of male labor force)",SL.UEM.TOTL.MA.ZS,2018,1.966000e+00
22,Montenegro,MNE,"Unemployment, total (% of total labor force)",SL.UEM.TOTL.ZS,2018,1.611600e+01
23,Myanmar,MMR,"Labor force, female (% of total labor force)",SL.TLF.TOTL.FE.ZS,2018,4.071705e+01
24,"Congo, Dem. Rep.",COD,"Unemployment, male (% of male labor force)",SL.UEM.TOTL.MA.ZS,2018,3.095000e+00
25,Vanuatu,VUT,"Unemployment, male (% of male labor force)",SL.UEM.TOTL.MA.ZS,2018,4.615000e+00
26,Upper middle income,UMC,"Labor force, total",SL.TLF.TOTL.IN,2018,1.331493e+09
27,Guinea,GIN,"Labor force, female (% of total labor force)",SL.TLF.TOTL.FE.ZS,2018,4.908887e+01
28,Kyrgyz Republic,KGZ,"Unemployment, female (% of female labor force)",SL.UEM.TOTL.FE.ZS,2018,8.918000e+00
29,Chad,TCD,"Unemployment, female (% of female labor force)",SL.UEM.TOTL.FE.ZS,2018,7.034000e+00

In [ ]:
bq_assistant.head("health_nutrition_population", num_rows=30)